const SPECIES = {
  bangus: {
    id: 'bangus',
    name: 'Bangus (Milkfish)',
    scientificName: 'Chanos chanos',
    salinityTolerance: { min: 0, max: 40, optimal: '20-30' },
    temperatureTolerance: { min: 20, max: 35, optimal: '27-30' },
    doMin: 3,
    ammoniaMax: 0.5,
    nitriteMax: 0.5,
    nitrateMax: 50,
    targetFCR: 1.5,
    targetSurvival: 85,
    targetDGR: '2-3 g/day',
    feedType: ['Starter', 'Grower', 'Finisher'],
    maturityDays: 120,
    harvestWeight: '300-400g',
    notes: 'Saline-tolerant, can be cultured in brackish water'
  },
  tilapiaSaltTolerant: {
    id: 'tilapiaSaltTolerant',
    name: 'Saline-Tolerant Tilapia',
    scientificName: 'Oreochromis niloticus',
    salinityTolerance: { min: 0, max: 35, optimal: '15-25' },
    temperatureTolerance: { min: 18, max: 35, optimal: '25-30' },
    doMin: 2.5,
    ammoniaMax: 0.5,
    nitriteMax: 0.5,
    nitrateMax: 50,
    targetFCR: 1.6,
    targetSurvival: 80,
    targetDGR: '1.5-2.5 g/day',
    feedType: ['Starter', 'Grower', 'Finisher'],
    maturityDays: 150,
    harvestWeight: '200-300g',
    notes: 'More saline-tolerant than Nile tilapia'
  },
  tilapiaSpinYY: {
    id: 'tilapiaSpinYY',
    name: 'SPIN YY Tilapia',
    scientificName: 'Oreochromis niloticus',
    salinityTolerance: { min: 0, max: 30, optimal: '10-20' },
    temperatureTolerance: { min: 18, max: 35, optimal: '25-30' },
    doMin: 2.5,
    ammoniaMax: 0.5,
    nitriteMax: 0.5,
    nitrateMax: 50,
    targetFCR: 1.4,
    targetSurvival: 90,
    targetDGR: '2-3 g/day',
    feedType: ['Starter', 'Grower', 'Finisher'],
    maturityDays: 130,
    harvestWeight: '250-350g',
    notes: 'All-male tilapia, faster growth, better FCR'
  },
  shrimp: {
    id: 'shrimp',
    name: 'Shrimp (Sugpo/Vanamei)',
    scientificName: 'Penaeus vannamei',
    salinityTolerance: { min: 0, max: 45, optimal: '25-35' },
    temperatureTolerance: { min: 20, max: 33, optimal: '28-32' },
    doMin: 4,
    ammoniaMax: 0.3,
    nitriteMax: 0.3,
    nitrateMax: 30,
    targetFCR: 1.2,
    targetSurvival: 70,
    targetDGR: '0.5-1 g/day',
    feedType: ['Starter', 'Grower', 'Finisher', 'Specialty'],
    maturityDays: 90,
    harvestWeight: '30-40g',
    notes: 'High-value species, sensitive to water quality'
  },
  mudCrab: {
    id: 'mudCrab',
    name: 'Mud Crab',
    scientificName: 'Scylla serrata',
    salinityTolerance: { min: 10, max: 35, optimal: '20-30' },
    temperatureTolerance: { min: 22, max: 35, optimal: '26-32' },
    doMin: 3,
    ammoniaMax: 0.5,
    nitriteMax: 0.5,
    nitrateMax: 50,
    targetFCR: 2.0,
    targetSurvival: 60,
    targetDGR: '0.5-1.5 g/day',
    feedType: ['Trash Fish', 'Pelleted Feed', 'Mollusks'],
    maturityDays: 180,
    harvestWeight: '200-400g',
    notes: 'Cannibalistic - requires shelters/hides'
  },
  oyster: {
    id: 'oyster',
    name: 'Single Shell Oyster',
    scientificName: 'Crassostrea iredalei',
    salinityTolerance: { min: 15, max: 35, optimal: '25-30' },
    temperatureTolerance: { min: 18, max: 32, optimal: '24-28' },
    doMin: 4,
    ammoniaMax: 0.3,
    nitriteMax: 0.3,
    nitrateMax: 30,
    targetFCR: null, // Filter feeders - no feed input
    targetSurvival: 70,
    targetDGR: null,
    feedType: ['Phytoplankton'], // Natural filter feeding
    maturityDays: 180,
    harvestWeight: '50-100g',
    notes: 'Filter feeder - improves water quality. No feed cost.'
  }
};
